### ISSUE TITLE
How to set submission style version for double blind review

### ISSUE THREAD

**Issue by leftthomas** [vtex-soft/texsupport.iospress-ecai#1]
The command `\ecaisubmission` is not work

**Comment by leftthomas** [comment]
@mingiss , The following parts should not appear in the submission, right? And I didn't see where is the submission  number on your posted pdf file
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/9991443/229476810-c5507a1d-63ec-408c-84ea-5eaa0536d534.png">

**Comment by mingiss** [comment]
As I was informed by our production manager, neither submission number, nor hiding the authors section were not in publishers requirements, while adapting the project class to the production markup syntax. You can comment authors manually, for now I've added hiding the orcid prefix if there are no authors:

https://github.com/vtex-soft/texsupport.iospress-ecai/blob/master/ecai.cls

If you have questions or proposals to the functionality of the class, please contact the IOS press representatives directly.

Best regards, 
Mindaugas Piešina, 
VTEX programmer.

**Comment by leftthomas** [comment]
According to ECAI 2023 submission requirements, the submitted paper should be  DOUBLE BLIND, which means the author details should not appear in the paper, and I didn't find how to  achieve this by using the provided template. According to convention (eg, CVPR), double blind submissions should not include author information, only submission ID and number of lines in review phase. Do I understand correctly?

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/9991443/229668319-6a7ea504-e82c-42f5-b3d3-766f4bf759ff.png">

<img width="1194" alt="image" src="https://user-images.githubusercontent.com/9991443/229668385-4f821914-8051-4dcf-bc8d-2ddafd8bdb1b.png">

**Comment by mingiss** [comment]
We have contacted the publisher and conference authorities, they agreed, that the additional features need to be implemented. I have added a class option [doubleblind] for the submission mode and a new command \paperid{} for the submission number. Look the preliminary files attached. Thanks for the contribution.
[ecai_20230406_2.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/11182705/ecai_20230406_2.zip)

**Comment by leftthomas** [comment]
@mingiss Thank you for your careful answer.
