### ISSUE TITLE
Not able to load /newtheorem{lemma}{Lemma} 

### ISSUE THREAD

**Issue by manvibharat** [vtex-soft/texsupport.iospress-ecai#2]
Hi I am not able to load add Lemma and definition. 
If I add 
\newtheorem{definition}{Definition}
\newtheorem{lemma}{Lemma}
in the .tex file i get the following error

I also tried 
\newtheorem{thm1}{Theorem}[section]
\newtheorem{thm2}{Theorem}[section]

\newtheorem{lemma}[thm1]{Lemma}
\newtheorem{definition}[thm2]{Definition}

I get the error called "LaTeX Error: No counter 'Theorem' defined"

**Comment by manvibharat** [comment]
Along with above issue. I am not able to load amsthm package form where I need Proof environment. It gives same error.

**Comment by manvibharat** [comment]
%% from here-------------------------
\makeatletter
\DeclareRobustCommand{\qed}{%
  \ifmmode % if math mode, assume display: omit penalty etc.
  \else \leavevmode\unskip\penalty9999 \hbox{}\nobreak\hfill
  \fi
  \quad\hbox{\qedsymbol}}
\newcommand{\openbox}{\leavevmode
  \hbox to.77778em{%
  \hfil\vrule
  \vbox to.675em{\hrule width.6em\vfil\hrule}%
  \vrule\hfil}}
\newcommand{\qedsymbol}{\openbox}
\newenvironment{proof}[1][\proofname]{\par
  \normalfont
  \topsep6\p@\@plus6\p@ \trivlist
  \item[\hskip\labelsep\itshape
    #1.]\ignorespaces
}{%
  \qed\endtrivlist
}
\newcommand{\proofname}{Proof}
\makeatother
%% upto here----------------------------
\begin{document}
  \begin{proof}
    This is a proof
  \end{proof}
\end{document}

This worked

**Comment by mingiss** [comment]
What distribution of Tex do you use? For me works fine, either in texlive 2021, or in Miktex.
[ecai-sample-and-instructions.pdf](https://github.com/vtex-soft/texsupport.iospress-ecai/files/11239504/ecai-sample-and-instructions.pdf)
[ecai-sample-and-instructions.tex.txt](https://github.com/vtex-soft/texsupport.iospress-ecai/files/11239505/ecai-sample-and-instructions.tex.txt)
