### ISSUE TITLE
table* uses larger font size than table

### ISSUE THREAD

**Issue by AwesomeLemon** [vtex-soft/texsupport.iospress-ecai#3]
I noticed that the font size in the table* environment (two-column tables) is larger than in the table environment (one-column tables). The guidelines don't mention this difference, so I guess it's a bug?

**Comment by mingiss** [comment]
Fixed, look the files attached.

[starred_table.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/11355046/starred_table.zip)

**Comment by mingiss** [comment]
The repo updated:
