### ISSUE TITLE
Figure : and Figure .

### ISSUE THREAD

**Issue by CHANGgreenEVER** [vtex-soft/texsupport.iospress-ecai#4]
I use     \usepackage{caption}   \usepackage{subcaption}   to create multiple images, but some errors appear

![image](https://user-images.githubusercontent.com/108571143/236419865-169ed09b-f11e-495e-b0d9-9573186fbb13.png)

**Comment by CHANGgreenEVER** [comment]
not  
![image](https://user-images.githubusercontent.com/108571143/236420026-4f509dc9-73ce-43b1-a635-f782cd5757e7.png)
and table is samle case

**Comment by mingiss** [comment]
Hello.

Have checked it. No errors appeared. Option [labelsep=period] to the package {caption} could be used to set the proper delimiter.
Look the example: [period.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/11420251/period.zip)

Regards, Mindaugas.

**Comment by CHANGgreenEVER** [comment]
Thank you so much! But it seems that the text is not centered anymore....
![image](https://user-images.githubusercontent.com/108571143/236804363-d0b008f8-62d2-4fa4-a1db-4c474fd1bcdd.png)

**Comment by mingiss** [comment]
I'm not familiar with the package {caption}. Refer to the documentation for details:
https://mirror.datacenter.by/pub/mirrors/CTAN/macros/latex/contrib/caption/caption.pdf

**Comment by CHANGgreenEVER** [comment]
Thank you very much for your help

**Comment by mingiss** [comment]
Look the answer in the next issue:

**Comment by mingiss** [comment]
done
