### ISSUE TITLE
Hyperref breaks caption formatting

### ISSUE THREAD

**Issue by AwesomeLemon** [vtex-soft/texsupport.iospress-ecai#5]
Hi, I'd like to use the hyperref package to make links clickable, but it changes the caption style of figures.
Without hyperref:

![image](https://user-images.githubusercontent.com/8983709/236855422-5515d10b-a72f-4c5c-a14d-98e047034115.png)

With hyperref:

![image](https://user-images.githubusercontent.com/8983709/236855580-6b24b380-f247-46e1-be95-8fe3dfeb7a54.png)

I wasn't able to solve this problem, could you give any advice?

**Comment by mingiss** [comment]
Hello.

May be package {caption} could help: 
[centered.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/11422621/centered.zip)

Regards, Mindaugas.

**Comment by AwesomeLemon** [comment]
That worked, thanks a lot!
