### ISSUE TITLE
How to remove the ORCiD ID for the camera-ready version?

### ISSUE THREAD

**Issue by chenguanqi** [vtex-soft/texsupport.iospress-ecai#6]
The latex file states that the use of \orcid{} is optional. So I didn't use it. But the compiled file still shows the ORCiD ID after the affiliation information. 
![image](https://github.com/vtex-soft/texsupport.iospress-ecai/assets/30858327/f31f0042-ced3-4b95-b777-c373b5adff60)
![image](https://github.com/vtex-soft/texsupport.iospress-ecai/assets/30858327/0151aad1-e482-4640-842f-33c36f8d002d)
So, how to remove the ORCiD ID for the camera-ready version?

**Comment by mingiss** [comment]
The shortage already fixed, download the updated class version:

https://github.com/vtex-soft/texsupport.iospress-ecai/blob/master/ecai.cls
