### ISSUE TITLE
How to add an "equal contribution" footnote for authors

### ISSUE THREAD

**Issue by xiaopeng-whu** [vtex-soft/texsupport.iospress-ecai#7]
According to the provided guidelines, I can use the \thanks command to designate the corresponding author. However, I couldn't find a way to indicate "equal contribution" among the first two authors. Using the \thanks command directly doesn't generate the correct format (i.e., a shared footnote symbol after the ordinal numbers of the first two authors). I would like to inquire if the template supports indicating "equal contribution" among authors.

The display I'm trying to achieve is similar to the image below:
![image](https://github.com/vtex-soft/texsupport.iospress-ecai/assets/45620521/1f28ce6d-3954-4cf6-b15f-af92b4260d8d)

**Comment by mingiss** [comment]
Hello.

What about using \footnote{} and \footnotemark with arabic indices?
Is that, what you expected?
The class is patched as well to support all three features -- \thanks, \footnote and references to the affiliation list.
Look the files attached.

Regards, Mindaugas.

[ecai-sample-and-instructions.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/12147829/ecai-sample-and-instructions.zip)

**Comment by mingiss** [comment]
It is not a problem, it's a feature ;)
Footnotes are customized a lot to deal with parallel indexing of affiliation (\address) and contribution (\thanks).
I could not find any way to incorporate the standard symbol numeration of the footnotes (*, †, ‡, §, etc.) to the logic of \thanks indexing -- the latter simply increments the number of stars: *, **, ***, etc. The first appearance of a \footnote would be the star (*), not the dagger (†) and conflict with the \thanks indexing. What about using of an optional parameter to the footnote commands and specify the index explicitly -- \footnote[\dagger]{...} and \footnotemark[\dagger]? I have added an implementation of them:

[ecai-sample-and-instructions_2.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/12163633/ecai-sample-and-instructions_2.zip)

**Comment by mingiss** [comment]
Template class updated:
https://github.com/vtex-soft/texsupport.iospress-ecai/blob/master/ecai.cls
