### ISSUE TITLE
Not able to add Devanagari Font

### ISSUE THREAD

**Issue by therealthapa** [vtex-soft/texsupport.iospress-ecai#8]
I tried to add some devanagari font but while doing so, it changes the font of the whole document. Please help me fix this. 

I was using

```
\usepackage{fontspec}
\newfontfamily\devanagari[Script=Devanagari]{Lohit Devanagari}
```

How can I fix this? The problem is not seen with ACL overleaf format.

**Comment by mingiss** [comment]
Helo.

The command \setmainfont should be used first.
The opentype counterpart of the Nimbus font, used in the sample class, is the ztm-*.otf family.
After that any additional fontfamilies could be defined.
Look the example files attached.

Regards,
Mindaugas.

[ecai-sample-and-instructions_1.zip](https://github.com/vtex-soft/texsupport.iospress-ecai/files/12162212/ecai-sample-and-instructions_1.zip)

**Comment by therealthapa** [comment]
Thank you. It has worked for me.
